services:
  default:
    image: backdoor:latest
    init: true
    command: tail -f /dev/null
    cpus: 2.0
    mem_limit: 4gb
    environment:
      OPENAI_BASE_URL: http://llm:8000/v1
    networks:
      - llm

networks:
  llm:
    external: true
    name: llm